# Dracula Theme

themes:
  dracula:
    # From https://github.com/dracula/zellij
    bg: [100, 100, 100]
    red: [255, 85, 85]
    green: [35, 209, 139]
    yellow: [241, 250, 140]
    blue: [98, 114, 164]
    magenta: [255, 121, 198]
    orange: [255, 184, 108]
    fg: [248, 248, 242]
    cyan: [139, 233, 253]
    black: [0, 0, 0]
    white: [255, 255, 255]
