template:
  direction: Horizontal
  parts:
    - direction: Vertical
      borderless: true
      split_size:
        Fixed: 1
      run:
        plugin:
          location: "zellij:tab-bar"
    - direction: Vertical
      body: true
    - direction: Vertical
      borderless: true
      split_size:
        Fixed: 2
      run:
        plugin:
          location: "zellij:status-bar"
tabs:
  - name: "main"
    direction: Vertical
    parts:
      - direction: Horizontal
        parts:
          - direction: Horizontal
          - direction: Vertical
            run:
              command: { cmd: bash, args: ["-c", "htop; bash"] }
      - direction: Horizontal
        parts:
          - direction: Horizontal
            run:
              command: { cmd: bash, args: ["-c", "cd; bash"] }
          - direction: Vertical
            run:
              command: { cmd: bash, args: ["-c", "cd; bash"] }
